export const LOADNEXT = 'BEERS/LOADNEXT';
export const REQUESTBEERS = 'BEERS/REQUESTBEERS';
export const SEARCHBEERS = 'BEERS/SEARCHBEERS';
export const ADDBEERS = 'BEERS/ADDBEERS';

export default {
  REQUESTBEERS, SEARCHBEERS, LOADNEXT, ADDBEERS,
};
