const INIT_FAVORITES = 'FAVORITES/INIT';
const ADD_FAVORITE = 'FAVORITES/ADD';
const REMOVE_FAVORITE = 'FAVORITES/REMOVE';
const CLEAR_FAVORITE = 'FAVORITES/CLEAR';
const UPDATE_FAVORITES = 'FAVORITES/UPDATE';

export {
  INIT_FAVORITES,
  ADD_FAVORITE,
  REMOVE_FAVORITE,
  UPDATE_FAVORITES,
  CLEAR_FAVORITE,
};
