const PRIMARY_COLOR = '#106cc8';
const PRIMARY_LIGHT_COLOR = '#5e9afc';
const PRIMARY_DARK_COLOR = '#004297';

const SECONDARY_COLOR = '#e0843c';
const SECONDARY_LIGHT_COLOR = '#ffb46a';
const SECONDARY_DARK_COLOR = '#a9560a';

const PRIMARY_TEXT_COLOR = '#ffffff';
const SECONDARY_TEXT_COLOR = '#000000';


export default {
  PRIMARY_COLOR,
  PRIMARY_LIGHT_COLOR,
  PRIMARY_DARK_COLOR,
  SECONDARY_COLOR,
  SECONDARY_LIGHT_COLOR,
  SECONDARY_DARK_COLOR,
  PRIMARY_TEXT_COLOR,
  SECONDARY_TEXT_COLOR,
};
